# Generated by Django 5.1 on 2024-08-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0004_doctormodel_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=100)),
                ('dosage', models.DecimalField(decimal_places=2, help_text='Dosage in ml', max_digits=5)),
                ('dose_count', models.IntegerField(help_text='Number of dosages required')),
                ('storage_temperature', models.DecimalField(decimal_places=1, help_text='Storage temperature in °C', max_digits=4)),
                ('expiration_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('vaccine_for', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], max_length=10)),
                ('vaccine_type', models.CharField(choices=[('inactivated', 'Inactivated Vaccine'), ('live_attenuated', 'Live Attenuated Vaccine'), ('subunit', 'Subunit Vaccine'), ('mRNA', 'mRNA Vaccine'), ('viral_vector', 'Viral Vector Vaccine'), ('toxoid', 'Toxoid Vaccine')], max_length=20)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='app_user.doctormodel')),
            ],
        ),
    ]
