# Generated by Django 5.1 on 2024-09-02 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='first_dose_date',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='book_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
