# Generated by Django 5.1 on 2024-09-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='book_date',
            new_name='first_dose_date',
        ),
    ]
