# Generated by Django 5.1 on 2024-09-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0003_comment_patient_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='patient_img',
            field=models.URLField(blank=True, default='person', null=True),
        ),
    ]
