# Generated by Django 5.1 on 2024-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0004_vaccinemodel_dose_gap_days_bookingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='patient',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='patient_age',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='patient_name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccinemodel',
            name='vaccine_type',
            field=models.CharField(choices=[('inactivated', 'Inactivated Vaccine'), ('live_attenuated', 'Live Attenuated Vaccine'), ('subunit', 'Subunit Vaccine'), ('mRNA', 'mRNA Vaccine'), ('viral_vector', 'Viral Vector Vaccine'), ('toxoid', 'Toxoid Vaccine'), ('hepatitis_b', 'Hepatitis B'), ('live_attenuated', 'Live attenuated'), ('recombinant', 'Recombinant'), ('inactivated_toxin', 'Inactivated toxin')], max_length=20),
        ),
    ]
