# Generated by Django 5.1 on 2024-09-04 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
        ('app_vaccine', '0004_alter_comment_patient_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcampaignmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookCampaing', to='app_user.patientmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='campaign',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_vaccine.vaccinecampaignmodel'),
        ),
    ]
