# Generated by Django 5.1 on 2024-09-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0005_bookingcampaignmodel_user_alter_comment_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCampaignAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_campaign', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TotalVaccineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vaccine', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
