# Generated by Django 5.1 on 2024-08-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0005_remove_bookingmodel_patient_bookingmodel_patient_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='dose_dates',
        ),
    ]
