# Generated by Django 5.1 on 2024-09-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0006_totalcampaignadded_totalvaccinemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcampaignmodel',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccinecampaignmodel',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccinemodel',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
