# Generated by Django 5.1 on 2024-09-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0008_alter_bookingcampaignmodel_id_alter_bookingmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
