# Generated by Django 5.1 on 2024-08-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0008_alter_bookingmodel_dose_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='dose_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='patient_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='patient_name',
            field=models.CharField(max_length=20),
        ),
    ]
