# Generated by Django 5.1 on 2024-09-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0009_alter_vaccinemodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalBookedOnCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_booked', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='totalcampaignadded',
            name='campaign_target',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccinemodel',
            name='vaccine_type',
            field=models.CharField(choices=[('inactivated', 'Inactivated Vaccine'), ('live_attenuated', 'Live Attenuated Vaccine'), ('subunit', 'Subunit Vaccine'), ('mRNA', 'mRNA Vaccine'), ('viral_vector', 'Viral Vector Vaccine'), ('toxoid', 'Toxoid Vaccine'), ('hepatitis_b', 'Hepatitis B'), ('live_attenuated', 'Live attenuated'), ('recombinant', 'Recombinant'), ('inactivated_toxin', 'Inactivated toxin'), ('polio-vaccine', 'Polio Vaccine')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccinetypemodel',
            name='vaccine_type',
            field=models.CharField(choices=[('inactivated', 'Inactivated Vaccine'), ('live_attenuated', 'Live Attenuated Vaccine'), ('subunit', 'Subunit Vaccine'), ('mRNA', 'mRNA Vaccine'), ('viral_vector', 'Viral Vector Vaccine'), ('toxoid', 'Toxoid Vaccine'), ('hepatitis_b', 'Hepatitis B'), ('live_attenuated', 'Live attenuated'), ('recombinant', 'Recombinant'), ('inactivated_toxin', 'Inactivated toxin'), ('polio-vaccine', 'Polio Vaccine')], max_length=20),
        ),
    ]
