# Generated by Django 5.1 on 2024-08-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0010_bookingcampaignmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingcampaignmodel',
            old_name='vaccine',
            new_name='campaign_name',
        ),
    ]
