# Generated by Django 5.1 on 2024-08-23 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0011_rename_vaccine_bookingcampaignmodel_campaign_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecampaignmodel',
            name='campaign_vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='app_vaccine.vaccinemodel'),
        ),
        migrations.AlterField(
            model_name='vaccinemodel',
            name='dose_gap_days',
            field=models.IntegerField(default=90, help_text='Gap between doses in days'),
        ),
    ]
