# Generated by Django 5.1 on 2024-09-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0011_alter_bookingcampaignmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecampaignmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
