# Generated by Django 5.1 on 2024-08-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
