# Generated by Django 5.1 on 2024-08-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0014_comment_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='patient_name',
            field=models.CharField(blank=True, default='person', max_length=30),
        ),
    ]
