# Generated by Django 5.1 on 2024-08-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0016_alter_vaccinecampaignmodel_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinemodel',
            name='vaccine_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/vaccine/'),
        ),
    ]
