# Generated by Django 5.1 on 2024-08-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0017_vaccinemodel_vaccine_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaignmodel',
            name='campaign_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/campaign/'),
        ),
    ]
