# Generated by Django 5.1 on 2024-08-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0018_vaccinecampaignmodel_campaign_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('inactivated', 'Inactivated Vaccine'), ('live_attenuated', 'Live Attenuated Vaccine'), ('subunit', 'Subunit Vaccine'), ('mRNA', 'mRNA Vaccine'), ('viral_vector', 'Viral Vector Vaccine'), ('toxoid', 'Toxoid Vaccine'), ('hepatitis_b', 'Hepatitis B'), ('live_attenuated', 'Live attenuated'), ('recombinant', 'Recombinant'), ('inactivated_toxin', 'Inactivated toxin')], max_length=20)),
                ('type_img', models.ImageField(blank=True, null=True, upload_to='images/vaccine/type')),
                ('tye_description', models.CharField(max_length=100)),
            ],
        ),
    ]
