# Generated by Django 5.1 on 2024-08-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0019_vaccinetypemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinetypemodel',
            name='tye_description',
            field=models.CharField(max_length=500),
        ),
    ]
