# Generated by Django 5.1 on 2024-08-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0020_alter_vaccinetypemodel_tye_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='bookingcampaignmodel',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
