# Generated by Django 5.1 on 2024-09-02 00:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0021_remove_comment_is_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecampaignmodel',
            name='campaign_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='campaign_img'),
        ),
        migrations.AlterField(
            model_name='vaccinemodel',
            name='vaccine_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='vaccine_img'),
        ),
        migrations.AlterField(
            model_name='vaccinetypemodel',
            name='type_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='type_img'),
        ),
    ]
