# Generated by Django 5.1 on 2024-09-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0022_alter_vaccinecampaignmodel_campaign_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingcampaignmodel',
            old_name='first_dose_date',
            new_name='start_date',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bookingcampaignmodel',
            name='dose_dates',
        ),
    ]
