# Generated by Django 5.1 on 2024-09-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccine', '0024_rename_start_date_bookingcampaignmodel_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcampaignmodel',
            name='book_date',
        ),
    ]
