# Generated by Django 5.1 on 2024-09-02 00:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='banner_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner_img'),
        ),
    ]
