# Generated by Django 5.1 on 2024-08-22 18:33

import app_user.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nid', models.IntegerField(validators=[app_user.validators.validate_nid])),
                ('phone_number', models.CharField(max_length=15, validators=[app_user.validators.validate_phone_number])),
                ('city', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('user_type', models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='patient', editable=False, max_length=10)),
                ('user_photo', models.ImageField(blank=True, upload_to='images/user/')),
                ('patient_id', models.CharField(blank=True, editable=False, max_length=6, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
