# Generated by Django 5.1 on 2024-08-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='patient', max_length=10),
        ),
    ]
