# Generated by Django 5.1 on 2024-09-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_remove_patientmodel_id_alter_patientmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPatientsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_patients', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
