# Generated by Django 5.1 on 2024-08-22 21:57

import app_user.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_patientmodel_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nid', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=15, validators=[app_user.validators.validate_phone_number])),
                ('city', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('specialization', models.CharField(choices=[('immunology', 'Immunology'), ('infectious_diseases', 'Infectious Diseases'), ('pediatrics', 'Pediatrics'), ('public_health', 'Public Health'), ('epidemiology', 'Epidemiology'), ('virology', 'Virology'), ('microbiology', 'Microbiology'), ('preventive_medicine', 'Preventive Medicine'), ('travel_medicine', 'Travel Medicine'), ('tropical_medicine', 'Tropical Medicine'), ('pharmacology', 'Pharmacology'), ('vaccine_development', 'Vaccine Development'), ('geriatrics', 'Geriatrics'), ('internal_medicine', 'Internal Medicine'), ('family_medicine', 'Family Medicine'), ('allergy_and_immunology', 'Allergy and Immunology'), ('occupational_medicine', 'Occupational Medicine'), ('health_policy_and_management', 'Health Policy and Management'), ('clinical_research', 'Clinical Research'), ('bioinformatics', 'Bioinformatics')], max_length=50)),
                ('license_number', models.CharField(max_length=8, unique=True, validators=[app_user.validators.validate_license_number])),
                ('user_type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='doctor', editable=False, max_length=10)),
                ('user_photo', models.ImageField(blank=True, upload_to='images/user/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
