# Generated by Django 5.1 on 2024-08-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_doctormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
