# Generated by Django 5.1 on 2024-08-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_doctormodel_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='doctor', max_length=10),
        ),
    ]
