# Generated by Django 5.1 on 2024-08-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_alter_doctormodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/'),
        ),
    ]
