# Generated by Django 5.1 on 2024-09-01 22:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_alter_doctormodel_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='user_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images/user'),
        ),
    ]
