# Generated by Django 5.1 on 2024-09-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_alter_patientmodel_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='user_photo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='user_photo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
