# Generated by Django 5.1 on 2024-09-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_alter_doctormodel_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='street_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='street_address',
            field=models.CharField(max_length=500),
        ),
    ]
