VACCINE_FOR=(
    ('adult','Adult'),
    ('child','Child'),
)
VACCINE_TYPE_CHOICES = [
    ('inactivated', 'Inactivated Vaccine'),
    ('live_attenuated', 'Live Attenuated Vaccine'),
    ('subunit', 'Subunit Vaccine'),
    ('mRNA', 'mRNA Vaccine'),
    ('viral_vector', 'Viral Vector Vaccine'),
    ('toxoid', 'Toxoid Vaccine'),
    ('hepatitis_b', 'Hepatitis B'),
    ('live_attenuated', 'Live attenuated'),
    ('recombinant', 'Recombinant'),
    ('inactivated_toxin', 'Inactivated toxin'),
]
# constants.py

BANGLADESH_DISTRICTS = [
    ('Barguna', 'Barguna'),
    ('Barishal', 'Barishal'),
    ('Bhola', 'Bhola'),
    ('Jhalokathi', 'Jhalokathi'),
    ('Patuakhali', 'Patuakhali'),
    ('Pirojpur', 'Pirojpur'),
    ('Bandarban', 'Bandarban'),
    ('Brahmanbaria', 'Brahmanbaria'),
    ('Chandpur', 'Chandpur'),
    ('Chattogram', 'Chattogram'),
    ('Cumilla', 'Cumilla'),
    ('Coxs_Bazar', 'Coxs_Bazar'),
    ('Feni', 'Feni'),
    ('Khagrachari', 'Khagrachari'),
    ('Lakshmipur', 'Lakshmipur'),
    ('Noakhali', 'Noakhali'),
    ('Rangamati', 'Rangamati'),
    ('Dhaka', 'Dhaka'),
    ('Faridpur', 'Faridpur'),
    ('Gazipur', 'Gazipur'),
    ('Gopalganj', 'Gopalganj'),
    ('Kishoreganj', 'Kishoreganj'),
    ('Madaripur', 'Madaripur'),
    ('Manikganj', 'Manikganj'),
    ('Munshiganj', 'Munshiganj'),
    ('Narayanganj', 'Narayanganj'),
    ('Narsingdi', 'Narsingdi'),
    ('Rajbari', 'Rajbari'),
    ('Shariatpur', 'Shariatpur'),
    ('Tangail', 'Tangail'),
    ('Bagerhat', 'Bagerhat'),
    ('Chuadanga', 'Chuadanga'),
    ('Jashore', 'Jashore'),
    ('Jhenaidah', 'Jhenaidah'),
    ('Khulna', 'Khulna'),
    ('Kushtia', 'Kushtia'),
    ('Magura', 'Magura'),
    ('Meherpur', 'Meherpur'),
    ('Narail', 'Narail'),
    ('Satkhira', 'Satkhira'),
    ('Jamalpur', 'Jamalpur'),
    ('Mymensingh', 'Mymensingh'),
    ('Netrokona', 'Netrokona'),
    ('Sherpur', 'Sherpur'),
    ('Bogura', 'Bogura'),
    ('Joypurhat', 'Joypurhat'),
    ('Naogaon', 'Naogaon'),
    ('Natore', 'Natore'),
    ('Chapai_Nawabganj', 'Chapai Nawabganj'),
    ('Pabna', 'Pabna'),
    ('Rajshahi', 'Rajshahi'),
    ('Sirajganj', 'Sirajganj'),
    ('Dinajpur', 'Dinajpur'),
    ('Gaibandha', 'Gaibandha'),
    ('Kurigram', 'Kurigram'),
    ('Lalmonirhat', 'Lalmonirhat'),
    ('Nilphamari', 'Nilphamari'),
    ('Panchagarh', 'Panchagarh'),
    ('Rangpur', 'Rangpur'),
    ('Thakurgaon', 'Thakurgaon'),
    ('Habiganj', 'Habiganj'),
    ('Maulvibazar', 'Maulvibazar'),
    ('Sunamganj', 'Sunamganj'),
    ('Sylhet', 'Sylhet'),
]
